name: ci

on:
  push:
    branches: docker

jobs:
  login:
    runs-on: ubuntu-latest
    steps:

      - name: Build
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      # Push to Github Container Registry
      - name: Push to Github Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          version: latest
          file: ./Dockerfile 
          push: true
          tags: ghcr.io/${{ github.repository }}:latest