name: Build and Publish Package

on: 
  push:
    branches:
    - master

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@master

    - name: Use Node.js 10.x
      uses: actions/setup-node@master
      with:
        version: 10.x
    - run: npm install
    - run: npm run build

    - name: Deploy with rsync
      uses: maxheld83/rsync@v0.1.1
      env:
        HOST_FINGERPRINT: ${{ secrets.HOST_FINGERPRINT }}
        HOST_IP: ${{ secrets.HOST_IP }}
        HOST_NAME: ${{ secrets.HOST_NAME }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} 
        SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      with: 
        args: $GITHUB_WORKSPACE/dist/ ${{ secrets.HOST_USER }}@$HOST_NAME:${{ secrets.DEPLOY_PATH }}

